/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ThinkersRouteImport } from './routes/thinkers'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FeedRouteImport } from './routes/feed'
import { Route as DiscernmentRouteImport } from './routes/discernment'
import { Route as CheckEmailRouteImport } from './routes/check-email'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as BibleRouteImport } from './routes/bible'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProfileUserIdRouteImport } from './routes/profile.$userId'
import { Route as BlogNewRouteImport } from './routes/blog_.new'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'

const ThinkersRoute = ThinkersRouteImport.update({
  id: '/thinkers',
  path: '/thinkers',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedRoute = FeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscernmentRoute = DiscernmentRouteImport.update({
  id: '/discernment',
  path: '/discernment',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckEmailRoute = CheckEmailRouteImport.update({
  id: '/check-email',
  path: '/check-email',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const BibleRoute = BibleRouteImport.update({
  id: '/bible',
  path: '/bible',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileUserIdRoute = ProfileUserIdRouteImport.update({
  id: '/profile/$userId',
  path: '/profile/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogNewRoute = BlogNewRouteImport.update({
  id: '/blog_/new',
  path: '/blog/new',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bible': typeof BibleRoute
  '/blog': typeof BlogRouteWithChildren
  '/check-email': typeof CheckEmailRoute
  '/discernment': typeof DiscernmentRoute
  '/feed': typeof FeedRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/thinkers': typeof ThinkersRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/new': typeof BlogNewRoute
  '/profile/$userId': typeof ProfileUserIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bible': typeof BibleRoute
  '/blog': typeof BlogRouteWithChildren
  '/check-email': typeof CheckEmailRoute
  '/discernment': typeof DiscernmentRoute
  '/feed': typeof FeedRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/thinkers': typeof ThinkersRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/new': typeof BlogNewRoute
  '/profile/$userId': typeof ProfileUserIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bible': typeof BibleRoute
  '/blog': typeof BlogRouteWithChildren
  '/check-email': typeof CheckEmailRoute
  '/discernment': typeof DiscernmentRoute
  '/feed': typeof FeedRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/thinkers': typeof ThinkersRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog_/new': typeof BlogNewRoute
  '/profile/$userId': typeof ProfileUserIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bible'
    | '/blog'
    | '/check-email'
    | '/discernment'
    | '/feed'
    | '/login'
    | '/settings'
    | '/thinkers'
    | '/auth/callback'
    | '/blog/$slug'
    | '/blog/new'
    | '/profile/$userId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bible'
    | '/blog'
    | '/check-email'
    | '/discernment'
    | '/feed'
    | '/login'
    | '/settings'
    | '/thinkers'
    | '/auth/callback'
    | '/blog/$slug'
    | '/blog/new'
    | '/profile/$userId'
  id:
    | '__root__'
    | '/'
    | '/bible'
    | '/blog'
    | '/check-email'
    | '/discernment'
    | '/feed'
    | '/login'
    | '/settings'
    | '/thinkers'
    | '/auth/callback'
    | '/blog/$slug'
    | '/blog_/new'
    | '/profile/$userId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BibleRoute: typeof BibleRoute
  BlogRoute: typeof BlogRouteWithChildren
  CheckEmailRoute: typeof CheckEmailRoute
  DiscernmentRoute: typeof DiscernmentRoute
  FeedRoute: typeof FeedRoute
  LoginRoute: typeof LoginRoute
  SettingsRoute: typeof SettingsRoute
  ThinkersRoute: typeof ThinkersRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  BlogNewRoute: typeof BlogNewRoute
  ProfileUserIdRoute: typeof ProfileUserIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/thinkers': {
      id: '/thinkers'
      path: '/thinkers'
      fullPath: '/thinkers'
      preLoaderRoute: typeof ThinkersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed': {
      id: '/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof FeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discernment': {
      id: '/discernment'
      path: '/discernment'
      fullPath: '/discernment'
      preLoaderRoute: typeof DiscernmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/check-email': {
      id: '/check-email'
      path: '/check-email'
      fullPath: '/check-email'
      preLoaderRoute: typeof CheckEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bible': {
      id: '/bible'
      path: '/bible'
      fullPath: '/bible'
      preLoaderRoute: typeof BibleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/$userId': {
      id: '/profile/$userId'
      path: '/profile/$userId'
      fullPath: '/profile/$userId'
      preLoaderRoute: typeof ProfileUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog_/new': {
      id: '/blog_/new'
      path: '/blog/new'
      fullPath: '/blog/new'
      preLoaderRoute: typeof BlogNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BibleRoute: BibleRoute,
  BlogRoute: BlogRouteWithChildren,
  CheckEmailRoute: CheckEmailRoute,
  DiscernmentRoute: DiscernmentRoute,
  FeedRoute: FeedRoute,
  LoginRoute: LoginRoute,
  SettingsRoute: SettingsRoute,
  ThinkersRoute: ThinkersRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  BlogNewRoute: BlogNewRoute,
  ProfileUserIdRoute: ProfileUserIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
